/*
 * Contenido del portfolio.
 * Todo el texto de la web sale de aquí: edítalo sin tocar el resto del código.
 * Cada idioma (es / en) tiene la misma estructura.
 */
window.PORTFOLIO = {
  name: 'Zulema Gutiérrez',
  email: 'zulema19gutierrez@gmail.com',
  linkedin: 'https://www.linkedin.com/in/zulema-guti%C3%A9rrez-504397312',
  github: 'https://github.com/Zulema1904',
  location: 'Coslada, Madrid',

  // Mascotas de escritorio (sprite: 'black' | 'tabby')
  pets: [
    {
      sprite: 'black',
      name: 'Thor',
      emoji: '⚡',
      bio: { es: 'dios del trueno y de pedir comida a las 6 de la mañana', en: 'god of thunder and of demanding breakfast at 6 am' },
    },
    {
      sprite: 'tabby',
      name: 'Hela',
      emoji: '👑',
      bio: { es: 'diosa de la muerte… y de la mantita del sofá', en: 'goddess of death… and of the sofa blanket' },
    },
  ],

  es: {
    docTitle: 'Zulema Gutiérrez · Desarrolladora Web',
    role: 'Desarrolladora Web · Técnica en Sistemas · IA',
    status: 'Abierta a nuevas oportunidades',
    about: [
      'Hola, soy Zulema 👋 Desarrolladora web con base en sistemas y redes.',
      'Empecé montando, configurando y dando soporte a equipos (SMR), seguí construyendo aplicaciones web (DAW) y hoy desarrollo software con inteligencia artificial.',
      'Me gusta entender cómo funcionan las cosas por dentro, del cable al navegador: investigar, aprender rápido y crear cosas nuevas.',
    ],
    facts: [
      ['Formación', 'DAW + SMR'],
      ['Ahora', 'Desarrollo en la UC3M'],
      ['Idiomas', 'Español · Inglés B1'],
    ],
    experience: [
      {
        period: 'Ene 2026 — Actualidad',
        role: 'Personal de actividades científico-técnicas',
        org: 'Universidad Carlos III de Madrid',
        points: [
          'Desarrollo de una aplicación de software con inteligencia artificial.',
          'Programación de scripts y desarrollo de aplicaciones de inteligencia artificial para un Doctorado Industrial.',
          'Análisis, modelado y propagación de modos de fallo para mejorar la fiabilidad de sistemas electrónicos.',
        ],
      },
      {
        period: 'Sep 2025 — Nov 2025',
        role: 'Programación y simulación electrónica',
        org: 'Power Smart Control',
        points: [
          'Scripts para generar e importar/exportar automáticamente esquemáticos y netlists en entornos de simulación.',
          'Software de simulación de electrónica de potencia: PSIM, NGSpice, LTspice, SIMBA, DSIM y QSpice.',
          'Gestión y adaptación de ficheros de diseño y simulación (esquemáticos, netlists, .xml, .txt…).',
          'Verificación y depuración de errores en flujos de trabajo entre herramientas.',
          'Machine learning con TensorFlow (Python) para reconocimiento de imágenes: entrenamiento y validación de modelos.',
          'Interfaces y prototipos en Python para pruebas de concepto antes de pasar a producción.',
        ],
      },
      {
        period: 'Mar 2023 — Jul 2023',
        role: 'Soporte técnico',
        org: 'Caredesk Soluciones S.L.',
        points: [
          'Soporte técnico a varias empresas.',
          'Uso de WordPress.',
          'Gestión de proyectos.',
          'Manejo de aplicaciones ofimáticas.',
        ],
      },
    ],
    education: [
      { period: '2023 — 2025', role: 'Grado Superior en Desarrollo de Aplicaciones Web (DAW)', org: 'IES Luis Braille' },
      { period: '2021 — 2023', role: 'Grado Medio en Sistemas Microinformáticos y Redes (SMR)', org: 'IES Luis Braille' },
    ],
    skills: [
      { title: 'Lenguajes', items: ['Java', 'JavaScript', 'Python', 'PHP', 'SQL'] },
      { title: 'Web y marcado', items: ['HTML5', 'CSS3', 'XML', 'WordPress'] },
      { title: 'Inteligencia artificial', items: ['TensorFlow', 'Machine learning', 'Reconocimiento de imágenes', 'Entrenamiento y validación de modelos'] },
      { title: 'Sistemas y redes', items: ['Sistemas operativos', 'Línea de comandos', 'Redes', 'Soporte técnico'] },
      { title: 'Simulación electrónica', items: ['PSIM', 'NGSpice', 'LTspice', 'SIMBA', 'DSIM', 'QSpice'] },
    ],
    soft: ['Resolución de problemas', 'Trabajo en equipo', 'Comunicación efectiva', 'Iniciativa', 'Aprendizaje rápido'],
    languages: [['Español', 'Nativo'], ['Inglés', 'Técnico · B1']],
    projects: [
      {
        name: 'ZulemaOS',
        kind: 'live',
        tag: 'En vivo',
        desc: 'Este portfolio: un sistema operativo retro en el navegador, con gestor de ventanas y terminal propios. Sin frameworks.',
        stack: ['HTML', 'CSS', 'JavaScript'],
      },
      {
        name: 'Automatización de netlists',
        kind: 'pro',
        tag: 'Profesional',
        desc: 'Scripts que generan, importan y exportan esquemáticos y netlists entre herramientas de simulación de electrónica de potencia.',
        stack: ['Python', 'XML', 'LTspice', 'PSIM'],
      },
      {
        name: 'Reconocimiento de imágenes',
        kind: 'pro',
        tag: 'Profesional',
        desc: 'Modelos de machine learning para reconocimiento de imágenes: preparación, entrenamiento y validación.',
        stack: ['Python', 'TensorFlow'],
      },
      {
        name: 'IA para fiabilidad electrónica',
        kind: 'pro',
        tag: 'Investigación',
        desc: 'Aplicaciones de IA para analizar y modelar la propagación de modos de fallo en sistemas electrónicos (Doctorado Industrial, UC3M).',
        stack: ['Python', 'IA'],
      },
    ],
    trash: [
      ['sindrome_del_impostor.exe', '2023'],
      ['miedo_a_preguntar.txt', '2024'],
      ['codigo_sin_comentar.js', '2025'],
      ['funciona_en_mi_maquina.zip', '2023'],
      ['console.log("aqui").js', '2024'],
      ['contraseña123.txt', '2021'],
      ['TFG_final_FINAL_v3_ahora_si.docx', '2025'],
      ['deploy_viernes_18h.log', '2025'],
      ['node_modules/  (4,2 GB)', '2026'],
    ],
    ui: {
      start: 'Inicio',
      quick: 'Modo rápido',
      langBtn: 'EN',
      langName: 'English',
      shutdown: 'Apagar',
      readme: 'Léeme',
      min: 'Minimizar',
      max: 'Maximizar',
      close: 'Cerrar',
      address: 'Dirección',
      apps: {
        welcome: 'Bienvenida.txt',
        about: 'Sobre_mi.txt',
        experience: 'Experiencia',
        projects: 'Proyectos',
        skills: 'Habilidades.exe',
        terminal: 'Terminal',
        contact: 'Contacto.exe',
        cv: 'CV.pdf',
        trash: 'Papelera',
      },
      paths: {
        experience: 'C:\\Zulema\\Experiencia',
        projects: 'C:\\Zulema\\Proyectos',
        trash: 'C:\\Papelera',
      },
      sec: {
        about: 'Sobre mí',
        experience: 'Experiencia',
        education: 'Formación',
        skills: 'Habilidades',
        soft: 'Aptitudes',
        languages: 'Idiomas',
        projects: 'Proyectos',
      },
      seeExperience: 'Ver experiencia',
      seeProjects: 'Ver proyectos',
      contactMe: 'Contactar',
      pending: 'Pendiente de completar',
      comingSoon: 'nuevo_proyecto.tmp',
      comingSoonText: 'Algo se está compilando…',
      welcome: {
        title: '¡Hola! Soy Zulema 👋',
        intro: 'Desarrolladora web y técnica en sistemas. Esto no es una web normal: es mi propio sistema operativo.',
        tips: [
          'Abre los iconos del escritorio. Las ventanas se pueden mover y cambiar de tamaño.',
          'Abre la {terminal} y escribe <code>help</code>.',
          '¿Tienes prisa? El {quick} muestra mi CV en una sola página.',
          'Mis dos gatos pasean por el escritorio. Haz clic en ellos 🐾',
        ],
        terminal: 'Terminal',
        quick: 'modo rápido',
        hide: 'No volver a mostrar',
        go: 'Empezar',
      },
      sys: {
        title: 'Propiedades del sistema',
        rows: [
          ['Sistema', 'ZulemaOS 1.0'],
          ['Registrado a', 'Zulema Gutiérrez'],
          ['Procesador', 'Curiosidad multinúcleo'],
          ['Memoria', 'SMR + DAW + IA'],
        ],
      },
      contact: {
        title: '¿Hablamos?',
        text: 'Estoy abierta a nuevas oportunidades como desarrolladora. Escríbeme y te respondo lo antes posible.',
        copy: 'Copiar',
        copied: '¡Copiado!',
        send: 'Enviar email',
      },
      trashNote: 'Aquí solo quedan cosas que ya no necesito 💜',
      trashDeleted: 'Eliminado en',
      quickBar: { back: 'Volver al escritorio', print: 'Imprimir / PDF' },
      pets: {
        meows: ['¡Miau!', 'Mrrrau', 'Prrr prrr 💜', '¿Comida?', 'Miau miau'],
        wake: 'Mrrr… 😾',
        on: 'Mascotas: sí',
        off: 'Mascotas: no',
      },
      shutdownMsg: 'Ya puedes cerrar la pestaña de forma segura.',
      reboot: 'Haz clic para reiniciar',
      bootSkip: 'Pulsa cualquier tecla para saltar',
      boot: {
        head: ['ZulemaBIOS v2.0.26  (C) 2021-2026 Zulema Gutiérrez', ''],
        checks: [
          ['CPU: Curiosidad multinúcleo', 'OK'],
          ['Memoria: SMR 2021-2023', 'OK'],
          ['Módulo DAW 2023-2025', 'OK'],
          ['Cargando IA / TensorFlow', 'OK'],
          ['Montando /home/zulema', 'OK'],
        ],
        tail: ['', 'Iniciando ZulemaOS…'],
      },
    },
  },

  en: {
    docTitle: 'Zulema Gutiérrez · Web Developer',
    role: 'Web Developer · Systems Technician · AI',
    status: 'Open to new opportunities',
    about: [
      'Hi, I\'m Zulema 👋 A web developer with a background in systems and networking.',
      'I started out setting up, configuring and supporting computers (SMR), moved on to building web applications (DAW), and today I develop AI-powered software.',
      'I like understanding how things work under the hood, from the cable to the browser: researching, learning fast and building new things.',
    ],
    facts: [
      ['Education', 'Web Dev + IT Systems'],
      ['Now', 'Developer at UC3M'],
      ['Languages', 'Spanish · English B1'],
    ],
    experience: [
      {
        period: 'Jan 2026 — Present',
        role: 'Scientific & Technical Staff',
        org: 'Universidad Carlos III de Madrid',
        points: [
          'Developing an AI-powered software application.',
          'Scripting and development of artificial intelligence applications for an Industrial PhD.',
          'Analysis, modelling and propagation of failure modes to improve the reliability of electronic systems.',
        ],
      },
      {
        period: 'Sep 2025 — Nov 2025',
        role: 'Programming & electronic simulation',
        org: 'Power Smart Control',
        points: [
          'Scripts to automatically generate, import and export schematics and netlists in simulation environments.',
          'Power electronics simulation software: PSIM, NGSpice, LTspice, SIMBA, DSIM and QSpice.',
          'Managing and adapting design and simulation files (schematics, netlists, .xml, .txt…).',
          'Verifying and debugging internal workflows between tools.',
          'Machine learning with TensorFlow (Python) for image recognition: model training and validation.',
          'User interfaces and Python prototypes for proofs of concept before production.',
        ],
      },
      {
        period: 'Mar 2023 — Jul 2023',
        role: 'IT Support',
        org: 'Caredesk Soluciones S.L.',
        points: [
          'Technical support for several companies.',
          'Working with WordPress.',
          'Project management.',
          'Office software.',
        ],
      },
    ],
    education: [
      { period: '2023 — 2025', role: 'Higher Technical Degree in Web Application Development (DAW)', org: 'IES Luis Braille' },
      { period: '2021 — 2023', role: 'Technical Degree in Microcomputer Systems and Networks (SMR)', org: 'IES Luis Braille' },
    ],
    skills: [
      { title: 'Languages', items: ['Java', 'JavaScript', 'Python', 'PHP', 'SQL'] },
      { title: 'Web & markup', items: ['HTML5', 'CSS3', 'XML', 'WordPress'] },
      { title: 'Artificial intelligence', items: ['TensorFlow', 'Machine learning', 'Image recognition', 'Model training & validation'] },
      { title: 'Systems & networking', items: ['Operating systems', 'Command line', 'Networking', 'IT support'] },
      { title: 'Electronic simulation', items: ['PSIM', 'NGSpice', 'LTspice', 'SIMBA', 'DSIM', 'QSpice'] },
    ],
    soft: ['Problem solving', 'Teamwork', 'Clear communication', 'Initiative', 'Fast learner'],
    languages: [['Spanish', 'Native'], ['English', 'Technical · B1']],
    projects: [
      {
        name: 'ZulemaOS',
        kind: 'live',
        tag: 'Live',
        desc: 'This portfolio: a retro operating system in the browser, with its own window manager and terminal. No frameworks.',
        stack: ['HTML', 'CSS', 'JavaScript'],
      },
      {
        name: 'Netlist automation',
        kind: 'pro',
        tag: 'Professional',
        desc: 'Scripts that generate, import and export schematics and netlists between power electronics simulation tools.',
        stack: ['Python', 'XML', 'LTspice', 'PSIM'],
      },
      {
        name: 'Image recognition',
        kind: 'pro',
        tag: 'Professional',
        desc: 'Machine learning models for image recognition: data preparation, training and validation.',
        stack: ['Python', 'TensorFlow'],
      },
      {
        name: 'AI for electronic reliability',
        kind: 'pro',
        tag: 'Research',
        desc: 'AI applications to analyse and model how failure modes propagate in electronic systems (Industrial PhD, UC3M).',
        stack: ['Python', 'AI'],
      },
    ],
    trash: [
      ['impostor_syndrome.exe', '2023'],
      ['fear_of_asking.txt', '2024'],
      ['uncommented_code.js', '2025'],
      ['works_on_my_machine.zip', '2023'],
      ['console.log("here").js', '2024'],
      ['password123.txt', '2021'],
      ['thesis_final_FINAL_v3_for_real.docx', '2025'],
      ['friday_5pm_deploy.log', '2025'],
      ['node_modules/  (4.2 GB)', '2026'],
    ],
    ui: {
      start: 'Start',
      quick: 'Quick view',
      langBtn: 'ES',
      langName: 'Español',
      shutdown: 'Shut down',
      readme: 'Read me',
      min: 'Minimize',
      max: 'Maximize',
      close: 'Close',
      address: 'Address',
      apps: {
        welcome: 'Welcome.txt',
        about: 'About_me.txt',
        experience: 'Experience',
        projects: 'Projects',
        skills: 'Skills.exe',
        terminal: 'Terminal',
        contact: 'Contact.exe',
        cv: 'CV.pdf',
        trash: 'Recycle Bin',
      },
      paths: {
        experience: 'C:\\Zulema\\Experience',
        projects: 'C:\\Zulema\\Projects',
        trash: 'C:\\RecycleBin',
      },
      sec: {
        about: 'About me',
        experience: 'Experience',
        education: 'Education',
        skills: 'Skills',
        soft: 'Soft skills',
        languages: 'Languages',
        projects: 'Projects',
      },
      seeExperience: 'See experience',
      seeProjects: 'See projects',
      contactMe: 'Get in touch',
      pending: 'To be completed',
      comingSoon: 'new_project.tmp',
      comingSoonText: 'Something is compiling…',
      welcome: {
        title: 'Hi! I\'m Zulema 👋',
        intro: 'Web developer and systems technician. This isn\'t a regular website: it\'s my very own operating system.',
        tips: [
          'Open the desktop icons. Windows can be dragged and resized.',
          'Open the {terminal} and type <code>help</code>.',
          'In a hurry? The {quick} shows my CV on a single page.',
          'My two cats roam the desktop. Give them a click 🐾',
        ],
        terminal: 'Terminal',
        quick: 'quick view',
        hide: 'Don\'t show again',
        go: 'Let\'s go',
      },
      sys: {
        title: 'System properties',
        rows: [
          ['System', 'ZulemaOS 1.0'],
          ['Registered to', 'Zulema Gutiérrez'],
          ['Processor', 'Multi-core curiosity'],
          ['Memory', 'SMR + DAW + AI'],
        ],
      },
      contact: {
        title: 'Let\'s talk',
        text: 'I\'m open to new opportunities as a developer. Drop me a line and I\'ll get back to you as soon as I can.',
        copy: 'Copy',
        copied: 'Copied!',
        send: 'Send email',
      },
      trashNote: 'Only things I no longer need end up here 💜',
      trashDeleted: 'Deleted in',
      quickBar: { back: 'Back to desktop', print: 'Print / PDF' },
      pets: {
        meows: ['Meow!', 'Mrrrow', 'Purr purr 💜', 'Food?', 'Meow meow'],
        wake: 'Mrrr… 😾',
        on: 'Pets: on',
        off: 'Pets: off',
      },
      shutdownMsg: 'It is now safe to close this tab.',
      reboot: 'Click to restart',
      bootSkip: 'Press any key to skip',
      boot: {
        head: ['ZulemaBIOS v2.0.26  (C) 2021-2026 Zulema Gutiérrez', ''],
        checks: [
          ['CPU: Multi-core curiosity', 'OK'],
          ['Memory: SMR 2021-2023', 'OK'],
          ['DAW module 2023-2025', 'OK'],
          ['Loading AI / TensorFlow', 'OK'],
          ['Mounting /home/zulema', 'OK'],
        ],
        tail: ['', 'Starting ZulemaOS…'],
      },
    },
  },
};
